
rabbitMQ:
  host: "rabbitmq"
  port: "5672"
  username: "user"
  password: "password"
  queue_name: "DICOM_Processor"

postgres:
  host: "dvh_db"
  port: "5432"
  username: "postgres"
  password: "postgres"
  db: "dvh_db"
  
GraphDB:
    host: "host.docker.internal"
    port: "7200"
    repo: "protrait"
API:
    host: "host.docker.internal"
    port: "8666"

xnat:
  host: "rabbitmq"
  localhost: "localhost"
  port: "5672"
  username: "user"
  password: "password"
  queue_name: "xnat"
  send_queue: "xnat"




dvh-calculations:
  -
    P-LUNG:
      roi: "Lung_L + Lung_R"
  -
    MeanDoseIpsiLateralParotidGland:
      roi: "Parotid_Ipsilateral"